import commutative_rings_defined_factorization_properties_foundation_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace commutative_rings_defined_factorization_properties_foundation_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end commutative_rings_defined_factorization_properties_foundation_canonical_lane_mathlib
end HautevilleHouse
